### ISSUE TITLE
LocalOccurrenceData doesn't read all records when a field in a csv contains a ' + support csv2

### ISSUE THREAD

**Issue by samuelbosch** [zoonproject/modules#66]
Currently read.table is used for reading csv files but the default arguments for read.csv and read.table are different which makes gives the situation that some csv files can be read by read.csv and not by read.table for instance when a field contains a ' as the quote default for read.table contains '. Secondly read.csv2 (separator=";" and decimal=",") is not supported with the current implementation.
Possible solutions:
- allowing a dataframe as input
- allowing passing in extra parameters for the read.table function using the ...
- using read.csv when extension is ".csv"
- using the read.csv defaults when calling read.table

**Comment by timcdlucas** [comment]
Hi,

Thanks a lot. I'll have a think about what's best.

I think the dataframe input is probably a useful feature but this module should also accept a filename. I'm not sure if the dataframe as input should be a separate module or not.

**Comment by timcdlucas** [comment]
The PR hasn't dealt with data frames in the workspace. I'll have a think about that. 

But it does fix the other issues.
