### ISSUE TITLE
LocalRaster depends on rapport package, causing error.

### ISSUE THREAD

**Issue by RTbecard** [zoonproject/modules#69]
In line 17 of `LocalRaster.r` the line `if(is.string(rasters)){` causes an error due to the dependancy on the `rapport` package.

I changed this to `  if(is.character(filenames)){` in my local repo and it seemed to do the trick, as its a `base` function.  Also, from what I can tell, it can differentiate between lists of strings and strings, so I think this should work fine here.

**Comment by timcdlucas** [comment]
That's actually `assertthat::is.string`.

The difference is that `is.string` checks for a length one character vector.

So `if (is.character(filenames) && length(filenames) == 1){` would be better. A vector of length > 1 would have to be dealt with differently and would possibly be clearer as `Chain`ed modules.

If you'd like to add that and make a PR I'll pull those changes. Otherwise one of us will change it when we can.

Thank you very much!

Thanks!

**Comment by RTbecard** [comment]
Sounds cool!  Whats the protocol for pushing updates?  Should I just make a new branch with the update and push that?

**Comment by timcdlucas** [comment]
Hi, make a new branch on your fork and push changes to that branch. If you then make a pull request from that branch we'll check the changes and accept.

Having a separate branch for the pull request is useful. If we have comments or anything we'd like you to change, you can change them on that branch and the pull request will automatically update. If you make a pull request from the master branch on your fork, then any changes you might make between making the pull request and it being accepted will (same as above) be automatically added to the pull request, which can be annoying. Hope that's clear!

Tim

**Comment by RTbecard** [comment]
Got it!  I'm also made changes to load rasters as variables from the global environment if the files don't exist.  Is this something I should also include in the PR?  Or is there already another method to deal with rasters saved as local variables in memory?

```r
  if(is.character(filenames) && length(filenames) == 1){
    ## Check if file exists
    if(file.exists(filenames)){
      ## Load raster from file
      raster <- raster(filenames)
    }else{
      ## Load raster from global environment
      raster <- eval(parse(text = filenames),envir = globalenv())
    }
  } else if(is.list(filenames)) {
    rasterList <- lapply(filenames, raster)
    raster <- stack(rasterList)
  }
```

**Comment by timcdlucas** [comment]
Yes I think this could be included in the PR. All changes are looking good!

**Comment by timcdlucas** [comment]
I'm having another look and other modules use `assertthat`.

You could just do `zoon:::GetPackage('assertthat')` at the top of the function. It's easier and more leaves more readable code.

**Comment by RTbecard** [comment]
Sounds good!  I'll make a PR tonight with the changes
