### ISSUE TITLE
MAXENT 

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/modules#9]
Lots of weird stuff happens with MAXENT in BiomodModel

    sdm <- workflow(SpOcc(species = 'Eresus sandaliatus', extent = c(-10, 45, 10, 65), databases = 'gbif'), 
                    Bioclim(extent = c(-10, 45, 10, 65)), 
                    OneHundredBackground, 
                    BiomodModel(modelType = 'MAXENT'), 
                    SurfaceMap
                    )
gives subset error.

    Error in modOut[[i]][[j]][[k]]: subscript out of bounds

I think this is a bug in biomod. There's some stuff [here](https://r-forge.r-project.org/forum/forum.php?set=custom&forum_id=995&style=nested&max_rows=100&submit=Change+View).

This just silently doesn't run the maxent.

    sdm <- workflow(SpOcc(species = 'Eresus sandaliatus', extent = c(-10, 45, 10, 65), databases = 'gbif'), 
                    Bioclim(extent = c(-10, 45, 10, 65)), 
                    OneHundredBackground, 
                    BiomodModel(modelType = c('MAXENT','GLM')), 
                    SurfaceMap
                    )

There's some other weird things happening.

**Comment by goldingn** [comment]
Stop it. You have a thesis to write!

On Tue, Mar 3, 2015 at 4:01 PM, Tim Lucas <notifications@github.com> wrote:

> Lots of weird stuff happens with MAXENT in BiomodModel
>
> sdm <- workflow(SpOcc(species = 'Eresus sandaliatus', extent = c(-10, 45, 10, 65), databases = 'gbif'),
>                 Bioclim(extent = c(-10, 45, 10, 65)),
>                 OneHundredBackground,
>                 BiomodModel(modelType = 'MAXENT'),
>                 SurfaceMap
>                 )
>
> gives subset error.
>
> Error in modOut[[i]][[j]][[k]]: subscript out of bounds
>
> I think this is a bug in biomod. There's some stuff here
> <https://r-forge.r-project.org/forum/forum.php?set=custom&forum_id=995&style=nested&max_rows=100&submit=Change+View>
> .
>
> This just silently doesn't run the maxent.
>
> sdm <- workflow(SpOcc(species = 'Eresus sandaliatus', extent = c(-10, 45, 10, 65), databases = 'gbif'),
>                 Bioclim(extent = c(-10, 45, 10, 65)),
>                 OneHundredBackground,
>                 BiomodModel(modelType = c('MAXENT','GLM')),
>                 SurfaceMap
>                 )
>
> There's some other weird things happening.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zoonproject/modules/issues/9>.
>



-- 
Nick Golding
Postdoctoral Researcher
Spatial Ecology & Epidemiology Group
Department of Zoology, University of Oxford
South Parks Road, Oxford OX1 3PS, UK

nick.golding@zoo.ox.ac.uk
+44(0)1865 271137
http://seeg.zoo.ox.ac.uk/

**Comment by goldingn** [comment]
this is mirrored in the zoon repo issues, and also closed.
